# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kwon/Documents/QT_mqtt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kwon/Documents/QT_mqtt/tls

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kwon/Documents/QT_mqtt/tls/CMakeFiles /home/kwon/Documents/QT_mqtt/tls//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kwon/Documents/QT_mqtt/tls/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named publisher

# Build rule for target.
publisher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 publisher
.PHONY : publisher

# fast build rule for target.
publisher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/build
.PHONY : publisher/fast

#=============================================================================
# Target rules for targets named subscriber

# Build rule for target.
subscriber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 subscriber
.PHONY : subscriber

# fast build rule for target.
subscriber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/build
.PHONY : subscriber/fast

#=============================================================================
# Target rules for targets named publisher_autogen

# Build rule for target.
publisher_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 publisher_autogen
.PHONY : publisher_autogen

# fast build rule for target.
publisher_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher_autogen.dir/build.make CMakeFiles/publisher_autogen.dir/build
.PHONY : publisher_autogen/fast

#=============================================================================
# Target rules for targets named subscriber_autogen

# Build rule for target.
subscriber_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 subscriber_autogen
.PHONY : subscriber_autogen

# fast build rule for target.
subscriber_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber_autogen.dir/build.make CMakeFiles/subscriber_autogen.dir/build
.PHONY : subscriber_autogen/fast

main_pub.o: main_pub.cpp.o
.PHONY : main_pub.o

# target to build an object file
main_pub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/main_pub.cpp.o
.PHONY : main_pub.cpp.o

main_pub.i: main_pub.cpp.i
.PHONY : main_pub.i

# target to preprocess a source file
main_pub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/main_pub.cpp.i
.PHONY : main_pub.cpp.i

main_pub.s: main_pub.cpp.s
.PHONY : main_pub.s

# target to generate assembly for a file
main_pub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/main_pub.cpp.s
.PHONY : main_pub.cpp.s

main_sub.o: main_sub.cpp.o
.PHONY : main_sub.o

# target to build an object file
main_sub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/main_sub.cpp.o
.PHONY : main_sub.cpp.o

main_sub.i: main_sub.cpp.i
.PHONY : main_sub.i

# target to preprocess a source file
main_sub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/main_sub.cpp.i
.PHONY : main_sub.cpp.i

main_sub.s: main_sub.cpp.s
.PHONY : main_sub.s

# target to generate assembly for a file
main_sub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/main_sub.cpp.s
.PHONY : main_sub.cpp.s

publisher.o: publisher.cpp.o
.PHONY : publisher.o

# target to build an object file
publisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/publisher.cpp.o
.PHONY : publisher.cpp.o

publisher.i: publisher.cpp.i
.PHONY : publisher.i

# target to preprocess a source file
publisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/publisher.cpp.i
.PHONY : publisher.cpp.i

publisher.s: publisher.cpp.s
.PHONY : publisher.s

# target to generate assembly for a file
publisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/publisher.cpp.s
.PHONY : publisher.cpp.s

publisher_autogen/mocs_compilation.o: publisher_autogen/mocs_compilation.cpp.o
.PHONY : publisher_autogen/mocs_compilation.o

# target to build an object file
publisher_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/publisher_autogen/mocs_compilation.cpp.o
.PHONY : publisher_autogen/mocs_compilation.cpp.o

publisher_autogen/mocs_compilation.i: publisher_autogen/mocs_compilation.cpp.i
.PHONY : publisher_autogen/mocs_compilation.i

# target to preprocess a source file
publisher_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/publisher_autogen/mocs_compilation.cpp.i
.PHONY : publisher_autogen/mocs_compilation.cpp.i

publisher_autogen/mocs_compilation.s: publisher_autogen/mocs_compilation.cpp.s
.PHONY : publisher_autogen/mocs_compilation.s

# target to generate assembly for a file
publisher_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/publisher.dir/build.make CMakeFiles/publisher.dir/publisher_autogen/mocs_compilation.cpp.s
.PHONY : publisher_autogen/mocs_compilation.cpp.s

subscriber.o: subscriber.cpp.o
.PHONY : subscriber.o

# target to build an object file
subscriber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/subscriber.cpp.o
.PHONY : subscriber.cpp.o

subscriber.i: subscriber.cpp.i
.PHONY : subscriber.i

# target to preprocess a source file
subscriber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/subscriber.cpp.i
.PHONY : subscriber.cpp.i

subscriber.s: subscriber.cpp.s
.PHONY : subscriber.s

# target to generate assembly for a file
subscriber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/subscriber.cpp.s
.PHONY : subscriber.cpp.s

subscriber_autogen/mocs_compilation.o: subscriber_autogen/mocs_compilation.cpp.o
.PHONY : subscriber_autogen/mocs_compilation.o

# target to build an object file
subscriber_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/subscriber_autogen/mocs_compilation.cpp.o
.PHONY : subscriber_autogen/mocs_compilation.cpp.o

subscriber_autogen/mocs_compilation.i: subscriber_autogen/mocs_compilation.cpp.i
.PHONY : subscriber_autogen/mocs_compilation.i

# target to preprocess a source file
subscriber_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/subscriber_autogen/mocs_compilation.cpp.i
.PHONY : subscriber_autogen/mocs_compilation.cpp.i

subscriber_autogen/mocs_compilation.s: subscriber_autogen/mocs_compilation.cpp.s
.PHONY : subscriber_autogen/mocs_compilation.s

# target to generate assembly for a file
subscriber_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/subscriber.dir/build.make CMakeFiles/subscriber.dir/subscriber_autogen/mocs_compilation.cpp.s
.PHONY : subscriber_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... publisher_autogen"
	@echo "... subscriber_autogen"
	@echo "... publisher"
	@echo "... subscriber"
	@echo "... main_pub.o"
	@echo "... main_pub.i"
	@echo "... main_pub.s"
	@echo "... main_sub.o"
	@echo "... main_sub.i"
	@echo "... main_sub.s"
	@echo "... publisher.o"
	@echo "... publisher.i"
	@echo "... publisher.s"
	@echo "... publisher_autogen/mocs_compilation.o"
	@echo "... publisher_autogen/mocs_compilation.i"
	@echo "... publisher_autogen/mocs_compilation.s"
	@echo "... subscriber.o"
	@echo "... subscriber.i"
	@echo "... subscriber.s"
	@echo "... subscriber_autogen/mocs_compilation.o"
	@echo "... subscriber_autogen/mocs_compilation.i"
	@echo "... subscriber_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

